name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Ruff format & lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Sync dependencies with dev extras
        run: uv sync --locked --group dev

      - name: Check formatting with Ruff
        run: uv run ruff format --check .

      - name: Run Ruff lint checks
        run: uv run ruff check .

  package:
    name: Build & install package with uv
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Sync production dependencies
        run: uv sync --locked

      - name: Build distribution artifacts
        run: uv build

      - name: Create fresh install environment
        run: uv venv --python 3.12 .venv-install

      - name: Install built wheel into fresh environment
        run: uv pip install --python .venv-install dist/*.whl

      - name: Show installed package metadata
        run: uv pip show --python .venv-install qblog
