name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Install Ruff
      run: uv add --dev ruff
    
    - name: Run tests
      run: |
        # Add your test commands here
        # For now, just check if the app starts
        uv run python -c "import app; print('App imports successfully')"
    
    - name: Lint with Ruff
      run: |
        # Run Ruff linter
        uv run ruff check --output-format=github .
    
    - name: Format check with Ruff
      run: |
        # Check if code is formatted properly
        uv run ruff format --check .

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    
    - name: Install Ruff
      run: uv add --dev ruff
    
    - name: Security scan with Ruff
      run: |
        # Run Ruff with security-focused rules
        uv run ruff check --select=S,B,E9,F63,F7,F82 --output-format=github .
